# These are supported funding model platforms

github: aiekick
custom: ['https://www.paypal.com/donate?business=YCRUVFJ42HFBL&no_recurring=0&item_name=you+can+donate+what+you+want%2C%0Aif+you+want+help+me+continue+to+create+open+source+software.%0AThanks+for+your+help+%3A%29&currency_code=EUR']
